//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public int MAKQ { get; set; }
        public Nullable<int> MAMH { get; set; }
        public Nullable<int> MAHOCSINH { get; set; }
        public Nullable<int> DIEMKT { get; set; }
        public Nullable<double> DIEMTHILAN1 { get; set; }
        public Nullable<double> DIEMTHILAN2 { get; set; }
        public Nullable<double> DIEMTB { get; set; }
        public string XEPLOAI { get; set; }
        public Nullable<int> MANAMHOC { get; set; }
        public Nullable<int> MAHOCKI { get; set; }
        public Nullable<int> MALOP { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public Nullable<int> DELETED_BY { get; set; }
    }
}
