//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPhamChiTiet
    {
        public int MAVPCT { get; set; }
        public Nullable<int> MAVIPHAM { get; set; }
        public Nullable<int> MALOI { get; set; }
        public string TENLOI { get; set; }
        public Nullable<int> DIEM { get; set; }
        public Nullable<int> MAHS { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public Nullable<int> DELETED_BY { get; set; }
    }
}
