//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPham
    {
        public int MAVIPHAM { get; set; }
        public Nullable<System.DateTime> NGAYVIPHAM { get; set; }
        public Nullable<int> TONGSOLOI { get; set; }
        public Nullable<int> TONGDIEM { get; set; }
        public Nullable<int> MALOP { get; set; }
        public Nullable<int> MANAMHOC { get; set; }
        public Nullable<int> MAHK { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> DELETEDBY { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
    }
}
